import { useState, type ReactNode } from "react";
import { Pressable, StyleSheet, Text, View, type StyleProp, type ViewStyle } from "react-native";
import { MinusIcon, PlusIcon } from "../icons/index.js";
import { tokens, useArcSynTheme } from "../theme.js";
export interface AccordionItem { value: string; title: string; content: ReactNode; disabled?: boolean; }
export interface AccordionProps { items: AccordionItem[]; value?: string[]; defaultValue?: string[]; onValueChange?: (value: string[]) => void; multiple?: boolean; disabled?: boolean; style?: StyleProp<ViewStyle>; }
export function Accordion({ items, value, defaultValue = [], onValueChange, multiple = false, disabled = false, style }: AccordionProps) {
  const [localValue, setLocalValue] = useState(defaultValue); const openItems = value ?? localValue; const { colors } = useArcSynTheme();
  function toggle(item: AccordionItem) { const isOpen = openItems.includes(item.value); const next = isOpen ? openItems.filter((entry) => entry !== item.value) : multiple ? [...openItems, item.value] : [item.value]; if (value === undefined) setLocalValue(next); onValueChange?.(next); }
  return <View style={[styles.root, { borderTopColor: colors.border }, style]}>{items.map((item) => { const open = openItems.includes(item.value); const itemDisabled = disabled || item.disabled; return <View key={item.value} style={[styles.item, { borderBottomColor: colors.border }]}><Pressable accessibilityRole="button" accessibilityState={{ disabled: itemDisabled, expanded: open }} disabled={itemDisabled} onPress={() => toggle(item)} style={styles.trigger}><Text style={[styles.title, { color: colors.foreground, fontFamily: tokens.fontFamily.sansSemibold }]}>{item.title}</Text>{open ? <MinusIcon accessible={false} color={colors.mutedForeground} size={18} /> : <PlusIcon accessible={false} color={colors.mutedForeground} size={18} />}</Pressable>{open ? <View style={styles.panel}>{typeof item.content === "string" ? <Text style={[styles.content, { color: colors.mutedForeground, fontFamily: tokens.fontFamily.sans }]}>{item.content}</Text> : item.content}</View> : null}</View>; })}</View>;
}
const styles = StyleSheet.create({ root: { borderTopWidth: 1 }, item: { borderBottomWidth: 1 }, trigger: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", minHeight: 44, paddingVertical: tokens.spacing[3] }, title: { fontSize: tokens.fontSize.sm }, panel: { paddingBottom: tokens.spacing[4] }, content: { fontSize: tokens.fontSize.sm, lineHeight: 21 } });
