import { type ReactNode } from "react";
import { StyleSheet, Text, View, type ViewProps } from "react-native";
import { tokens, useArcSynTheme } from "../theme.js";
import { Skeleton } from "./skeleton.js";
import { StatusIndicator, type StatusIndicatorStatus } from "./status-indicator.js";
export interface ActivityFeedItem { id: string; avatar?: ReactNode; icon?: ReactNode; title: ReactNode; description?: ReactNode; timestamp?: ReactNode; status?: StatusIndicatorStatus; actions?: ReactNode; accessibilityLabel?: string; }
export interface ActivityFeedProps extends ViewProps { items: readonly ActivityFeedItem[]; mode?: "feed" | "timeline"; compact?: boolean; loading?: boolean; loadingCount?: number; empty?: ReactNode; }
export function ActivityFeed({ items, mode = "feed", compact = false, loading = false, loadingCount = 3, empty, style, ...props }: ActivityFeedProps) {
  const { colors } = useArcSynTheme();
  if (loading) return <View accessibilityState={{ busy: true }} style={[styles.root, style]} {...props}>{Array.from({ length: loadingCount }, (_, index) => <View key={index} style={styles.item}><Skeleton variant="circular" height={32} width={32} /><View style={styles.body}><Skeleton height={14} width="55%" /><Skeleton height={12} width="80%" /></View></View>)}</View>;
  if (!items.length) return <View style={[styles.empty, style]}><Text style={{ color: colors.mutedForeground }}>{empty}</Text></View>;
  return <View accessibilityRole="list" style={[styles.root, style]} {...props}>{items.map((item, index) => <View key={item.id} accessibilityLabel={item.accessibilityLabel} style={[styles.item, compact && styles.compact, index > 0 && { borderTopColor: colors.border, borderTopWidth: mode === "feed" ? 1 : 0 }]}>{mode === "timeline" && index < items.length - 1 ? <View accessible={false} style={[styles.line, { backgroundColor: colors.border }]} /> : null}<View style={styles.marker}>{item.avatar ?? item.icon ?? (item.status ? <StatusIndicator status={item.status} iconOnly accessibleLabel={String(item.title)} /> : null)}</View><View style={styles.body}><Text style={[styles.title, { color: colors.foreground }]}>{item.title}</Text>{item.description ? <Text style={[styles.description, { color: colors.mutedForeground }]}>{item.description}</Text> : null}{item.timestamp ? <Text style={[styles.timestamp, { color: colors.mutedForeground }]}>{item.timestamp}</Text> : null}</View>{item.actions}</View>)}</View>;
}
const styles = StyleSheet.create({ root: {}, item: { alignItems: "flex-start", flexDirection: "row", gap: tokens.spacing[3], paddingVertical: tokens.spacing[3], position: "relative" }, compact: { gap: tokens.spacing[2], paddingVertical: tokens.spacing[2] }, marker: { alignItems: "center", justifyContent: "center", minHeight: 32, minWidth: 32, zIndex: 1 }, line: { bottom: -12, left: 16, position: "absolute", top: 16, width: 1 }, body: { flex: 1, gap: tokens.spacing[1] }, title: { fontFamily: tokens.fontFamily.sansSemibold, fontSize: tokens.fontSize.sm }, description: { fontSize: tokens.fontSize.xs }, timestamp: { fontSize: tokens.fontSize.xs }, empty: { alignItems: "center", minHeight: 112, justifyContent: "center" } });
