import { useState, type ReactNode } from "react";
import { Pressable, StyleSheet, Text, View, type StyleProp, type ViewStyle } from "react-native";
import { tokens, useArcSynTheme } from "../theme.js";

export interface RadioGroupOption { label: ReactNode; value: string; disabled?: boolean; }
export interface RadioGroupProps { options: RadioGroupOption[]; value?: string; defaultValue?: string; onValueChange?: (value: string) => void; disabled?: boolean; invalid?: boolean; orientation?: "horizontal" | "vertical"; variant?: "default" | "card"; accessibilityLabel?: string; style?: StyleProp<ViewStyle>; }

export function RadioGroup({ options, value, defaultValue, onValueChange, disabled = false, invalid = false, orientation = "vertical", variant = "default", accessibilityLabel, style }: RadioGroupProps) {
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue); const selectedValue = value ?? uncontrolledValue; const { colors } = useArcSynTheme();
  function choose(nextValue: string) { if (value === undefined) setUncontrolledValue(nextValue); onValueChange?.(nextValue); }
  return <View accessibilityRole="radiogroup" accessibilityLabel={accessibilityLabel} accessibilityState={{ disabled }} style={[styles.root, orientation === "horizontal" ? styles.horizontal : styles.vertical, style]}>{options.map((option) => { const isDisabled = disabled || option.disabled; const checked = selectedValue === option.value; const stateColor = invalid ? colors.danger : colors.primary; return <Pressable key={option.value} disabled={isDisabled} onPress={() => choose(option.value)} accessibilityRole="radio" accessibilityState={{ checked, disabled: isDisabled }} style={[styles.item, variant === "card" && styles.card, { opacity: isDisabled ? 0.5 : 1, backgroundColor: variant === "card" && checked ? colors.surfaceSunken : colors.surface, borderColor: variant === "card" && checked ? stateColor : invalid && variant === "card" ? colors.danger : colors.border }]}><View style={[styles.control, { backgroundColor: colors.surface, borderColor: invalid ? colors.danger : checked ? colors.primary : colors.borderStrong }]}>{checked ? <View style={[styles.indicator, { backgroundColor: stateColor }]} /> : null}</View><Text style={[styles.label, { color: colors.foreground, fontFamily: tokens.fontFamily.sans }]}>{option.label}</Text></Pressable>; })}</View>;
}

const styles = StyleSheet.create({ root: { gap: tokens.spacing[3] }, vertical: { flexDirection: "column" }, horizontal: { flexDirection: "row", flexWrap: "wrap" }, item: { alignItems: "center", flexDirection: "row", gap: tokens.spacing[2], minHeight: 28 }, card: { borderRadius: tokens.radius.md, borderWidth: 1, minHeight: 64, padding: tokens.spacing[3], width: "100%" }, control: { alignItems: "center", borderRadius: 9999, borderWidth: 1, height: 20, justifyContent: "center", width: 20 }, indicator: { borderRadius: 9999, height: 10, width: 10 }, label: { fontSize: tokens.fontSize.sm } });
