import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View, type StyleProp, type ViewStyle } from "react-native";
import { tokens, useArcSynTheme } from "../theme.js";

export interface SelectOption { label: string; value: string; disabled?: boolean; group?: string; }
export interface SelectProps { options: SelectOption[]; value?: string | null; defaultValue?: string | null; onValueChange?: (value: string) => void; placeholder?: string; disabled?: boolean; accessibilityLabel?: string; style?: StyleProp<ViewStyle>; }

export function Select({ options, value, defaultValue = null, onValueChange, placeholder = "Selecione uma opção", disabled = false, accessibilityLabel, style }: SelectProps) {
  const [open, setOpen] = useState(false); const [uncontrolledValue, setUncontrolledValue] = useState<string | null>(defaultValue); const selectedValue = value ?? uncontrolledValue;
  const selected = options.find((option) => option.value === selectedValue); const { colors } = useArcSynTheme(); let lastGroup: string | undefined;
  function choose(next: string) { if (value === undefined) setUncontrolledValue(next); onValueChange?.(next); setOpen(false); }
  return <><Pressable disabled={disabled} onPress={() => setOpen(true)} accessibilityRole="button" accessibilityLabel={accessibilityLabel} accessibilityState={{ disabled, expanded: open }} style={[styles.trigger, { backgroundColor: colors.surface, borderColor: colors.border, opacity: disabled ? 0.5 : 1 }, style]}><Text style={[styles.triggerText, { color: selected ? colors.foreground : colors.mutedForeground, fontFamily: tokens.fontFamily.sans }]}>{selected?.label ?? placeholder}</Text><Text style={[styles.icon, { color: colors.mutedForeground }]}>⌄</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={() => setOpen(false)}><Pressable style={[styles.backdrop, { backgroundColor: "rgba(8, 9, 16, 0.72)" }]} onPress={() => setOpen(false)}><Pressable style={[styles.sheet, { backgroundColor: colors.surfaceRaised, borderColor: colors.border }]} onPress={(event) => event.stopPropagation()}><ScrollView>{options.map((option) => { const group = option.group !== lastGroup ? option.group : undefined; lastGroup = option.group; return <View key={option.value}>{group ? <Text style={[styles.group, { color: colors.mutedForeground, fontFamily: tokens.fontFamily.sansSemibold }]}>{group}</Text> : null}<Pressable disabled={option.disabled} onPress={() => choose(option.value)} accessibilityRole="radio" accessibilityState={{ selected: selectedValue === option.value, disabled: option.disabled }} style={[styles.option, { opacity: option.disabled ? 0.45 : 1, backgroundColor: selectedValue === option.value ? colors.surfaceSunken : "transparent" }]}><Text style={[styles.optionText, { color: colors.foreground, fontFamily: tokens.fontFamily.sans }]}>{option.label}</Text>{selectedValue === option.value ? <Text style={{ color: colors.primary }}>✓</Text> : null}</Pressable></View>; })}</ScrollView></Pressable></Pressable></Modal></>;
}

const styles = StyleSheet.create({ trigger: { alignItems: "center", borderRadius: tokens.radius.md, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 44, paddingHorizontal: tokens.spacing[3] }, triggerText: { fontSize: tokens.fontSize.sm }, icon: { fontSize: 14 }, backdrop: { flex: 1, justifyContent: "flex-end" }, sheet: { borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, borderWidth: 1, maxHeight: "60%", padding: tokens.spacing[2] }, group: { fontSize: tokens.fontSize.xs, paddingHorizontal: tokens.spacing[2], paddingTop: tokens.spacing[3], textTransform: "uppercase" }, option: { alignItems: "center", borderRadius: tokens.radius.sm, flexDirection: "row", justifyContent: "space-between", minHeight: 44, paddingHorizontal: tokens.spacing[2] }, optionText: { fontSize: tokens.fontSize.sm } });
